guard updatedb command

diff --git a/build-iso b/build-iso
--- a/build-iso
+++ b/build-iso
@@ -1647,16 +1647,18 @@ do_stage_4() {
         fi
     fi
 
-    local update_cmd=updatedb
-    say "Run $update_cmd"
-    echo 3 | sudo tee /proc/sys/vm/drop_caches >/dev/null
-    sleep 2
-    mount -t tmpfs -o size=100k tmpfs /var/cache/apt/archives
-    $update_cmd --add-prunepaths /var/cache/apt/archives/ || error "The $(pqw $update_cmd) program failed"
-    $update_cmd || error "The $(pqw $update_cmd) program failed"
-    umount /var/cache/apt/archives
-    sleep 2
-    echo 3 | sudo tee /proc/sys/vm/drop_caches >/dev/null
+     if command -v updatedb >/dev/null 2>&1; then
+         local update_cmd=updatedb
+         say "Run $update_cmd"
+         echo 3 | sudo tee /proc/sys/vm/drop_caches >/dev/null
+         sleep 2
+         mount -t tmpfs -o size=100k tmpfs /var/cache/apt/archives
+         $update_cmd --add-prunepaths /var/cache/apt/archives/ || error "The $(pqw $update_cmd) program failed"
+         $update_cmd || error "The $(pqw $update_cmd) program failed"
+         umount /var/cache/apt/archives
+         sleep 2
+         echo 3 | sudo tee /proc/sys/vm/drop_caches >/dev/null
+     fi
     # We send on the exact kernel name we found
     echo "K_NAME=\"$K_NAME\"" > "$output_file"
 
